# Generated by Django 6.0.5 on 2026-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0002_recipe_shoppingitem_alter_userquery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('calories', models.IntegerField(default=0)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('cooking_time', models.CharField(max_length=100)),
                ('recipe_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
